### ISSUE TITLE
Undercounting of Ge77 in the Baseline Setup

### ISSUE THREAD

**Issue by MoritzNeuberger** [drbenmorgan/warwick-legend#36]
I found that at least in the baseline setup the number of Germanium 77 produced in the simulation and the number reported by the sensitive detector is different. When more than one Germanium 77 is produced in an event, it can occur that one or several of them are not stored. Specifically, this occurs when there are several events in one of the detector volumes. In that case, the most recent one seems to overwrite possible previous ones in the corresponding maps of the primitive scorer. I assume this due to GetIndex() not being defined in any of the primitive scorers and thus returns the copy number of the detector volumes. I think one could solve this issue by defining the GetIndex() function to return, for example, the TrackID.
![image](https://user-images.githubusercontent.com/31659079/116219774-46ac9280-a74c-11eb-978e-e42c92fed302.png)
Comment on the picture: I know there is a lot of additional output. I just added that one to investigate where the bug originated from. ^_^'

This bug became apparent after implementing an alternative way to register Germanium 77 in order to also get information on the neutron that produced it. As it does not use the sensitive detectors, it is not influenced by this bug.

**Comment by yramachers** [comment]
Hello @MoritzNeuberger ! Thanks for the issue post. The assumption from the start was that Ge-77 production ought to be very rare so checks on multiple production events in the same volume were not conducted. That is very helpful. You are right, the GetIndex will overwrite any existing entry, being the key in a std::map. I've had problems with that feature of primitive scorers in other applications. The scorers are very convenient but maybe a little too convenient for some applications. I think you make a good case for changes. Replacing the index with another unique integer like the track ID could work. One wouldn't really expect the same track producing 2 Ge-77 products.
Another approach I've used on a different project after some exasperation with the scorers is to simply go back to the classic SD and Hit objects where the Hit object simply stores anything of interest in one place and conditions are explicit. I can prepare a branch with that and see where that leads. Unfortunately term time has started again and there is little time available but it wouldn't be a big task given that I've done the same thing recently.
On the neutron parent issue, we've put that in the current code by way of Trajectory objects which store literally everything. That is problematic due to storage issues, there is simply so much to store but if you are only interested in the immediate parent neutron then that's maybe a bit too much information.

**Comment by yramachers** [comment]
Ok, on the GeSD branch I can see several Ge-77 isotope productions in a single event at times. That confirms your observation. A bit of code cleaning and the change to a SD object and a stored Hit object looks a lot cleaner to me. The Ge-77 filter is now in the SD explicitly coded. Not flexible but then it isn't meant to be flexible either.
The multi-production as such is quite re-affirming. It means the volume and placement of individual crystals does play a role. The next set of code changes will hence adapt the geometry to a more realistic placement of smaller Ge crystals instead of the lump 250kg blocks currently in the setup. That should have an effect on the number of multi-production events.

**Comment by yramachers** [comment]
The baseline and alternative geometries now have a suitable Ge array each. Biased running still gives a sizeable fraction of multiple Ge-77 production, apparently, to be checked. The Ge crystal units now have roughly 2.67 kg hence are significantly smaller units. A PR #37 has been submitted to address this current issue.
